### ISSUE TITLE
 the detail of function "get_predicted_texture" in texture.py

### ISSUE THREAD

**Issue by hangon666** [nabeel3133/3D-texture-fitting#2]
Hello, thanks for your share,
I can't find the Additional Results Section B.3 of the paper, 
and when I tried to read the code, I can't understand the detail of  function "get_predicted_texture" in texture.py，could you give me some advice?
Thanks a lot!

**Comment by nabeel3133** [comment]
Hello. Thank you for checking out the repository. Please refer to this PDF page no 11/14 (https://arxiv.org/pdf/1701.04851.pdf). Here, you will find the Additional Results Section B.3. Go through it and it will help you to understand the function "get_predicted_texture".

**Comment by hangon666** [comment]
Thanks for your reply, but I still can't understand this formula, could you explain it for me?
Thanks a lot!!!
![image](https://user-images.githubusercontent.com/58209788/76212770-2bc74800-6244-11ea-8a28-289216b5d86a.png)

**Comment by nabeel3133** [comment]
```
distances = []
for i in range(0, vertices_len):
			vertice1 = vertices[i,:]
			vertice2 = vertices[8317,:]
			distances.append(sqrt(pow(vertice2[0]-vertice1[0],2) + pow(vertice2[1]-vertice1[1],2) + pow(vertice2[2]-vertice1[2],2)))
```

8317 is the index of the nose vertex and distance of each vertex is calculated from nose vertex and appended in the list of distances. 

```
minimum = min(distances)
maximum = max(distances)

		for i in range(0, vertices_len):
			distances[i]=abs(((distances[i]-minimum)/(maximum-minimum)) - 1);
			distances[i]=(distances[i] * range1)
```  
Here we are normalizing all the distances. range1 variable tells us the weightage of the predicted texture during interpolation. 

```
weight1 = []
		for i in range(0,len(distances)):
			weight1.append(distances[i])
			weight1.append(distances[i])
			weight1.append(distances[i])
		
		weight2 = np.array([weight1]*np.shape(tex_PC)[1])
		weight1 = np.array(weight1)
		weight2 = np.transpose(weight2)
```
Here we are appending all the distances 3 times since each vertex has 3 coordinates to the weight1 list in order to get a list of 160K length. We need to multiply this list with the Texture Principal components that is "B" in equation 10 of the paper. So we generate an array having the shape of 160K x 199 and then transpose it to get the weight2 matrix having shape 199 x 160K. 

```
tex_MU = np.reshape(tex_MU,np.shape(tex_MU)[0])
tex_lhs = np.transpose(np.multiply(tex_PC, weight2))
tex_rhs = np.multiply((tex_Cp - tex_MU), weight1)
tex_z = np.matmul(tex_lhs,tex_rhs)
```

Here is the code of the screenshot you posted.
